"""
AI Analysis Tab for the Rule Analysis Report window.

Provides an AI-powered semantic analysis layer that complements the existing
static rule analyzer. Users can trigger AI deep analysis via Amazon Bedrock,
view structured findings organized by category, and hand off selected findings
to the AI Rule Assistant for rule generation.
"""

import logging
import os
import platform as _plat
import subprocess as _sp
import tempfile
import threading
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from typing import TYPE_CHECKING
import webbrowser

from src.agent.agent_factory import AgentFactory
from src.agent.ai_rule_analyzer import AIRuleAnalyzer
from src.agent.best_practice_checker import BestPracticeChecker
from src.agent.models import AnalysisFinding, StructuredAnalysisResponse
from src.analysis.rule_analyzer import RuleAnalyzer
from src.core.constants import BEDROCK_REGIONS

if TYPE_CHECKING:
    from suricata_generator import SuricataRuleGenerator

# Guard boto3 import — AI analysis degrades gracefully when absent
HAS_BOTO3 = False
try:
    import boto3
    HAS_BOTO3 = True
except ImportError:
    boto3 = None

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
#  Dark mode detection (follows ui-conventions.md pattern)
# ---------------------------------------------------------------------------
_is_dark = False
if _plat.system() == "Darwin":
    try:
        _r = _sp.run(
            ["defaults", "read", "-g", "AppleInterfaceStyle"],
            capture_output=True,
            text=True,
        )
        _is_dark = "Dark" in _r.stdout
    except Exception:
        pass


# ---------------------------------------------------------------------------
#  Disclaimer text (shared between UI and exports)
# ---------------------------------------------------------------------------
_DISCLAIMER_TEXT = (
    "AI analysis findings are generated by a large language model and may "
    "contain inaccuracies. All findings must be validated by a qualified "
    "security professional before acting on them."
)

# Section metadata: (key, display title, id prefix)
_SECTION_META = [
    ("coverage_gaps", "Coverage Gaps", "cg"),
    ("policy_coherence", "Policy Coherence", "pc"),
    ("optimizations", "Optimization Suggestions", "opt"),
    ("aws_advice", "AWS NFW Advice", "nfw"),
]

# Severity → emoji mapping for HTML export
_SEVERITY_HTML_ICONS = {
    "critical": "\U0001f6a8",  # 🚨
    "warning": "\u26a0\ufe0f",  # ⚠️
    "info": "\u2139\ufe0f",     # ℹ️
}


def generate_html_report(response: "StructuredAnalysisResponse") -> str:
    """Generate a self-contained HTML report from an AI analysis response.

    The returned HTML includes inline CSS, is organized by section, and
    contains severity icons, confidence badges, the AI disclaimer, and a
    timestamp.  It has no external dependencies so it can be saved as a
    single ``.html`` file or opened directly in a browser for PDF printing.

    This is a module-level function so it can be imported and tested
    independently of the ``AIAnalysisTab`` UI class.
    """
    from html import escape

    # ── Timestamp formatting ──────────────────────────────────────────
    timestamp_display = response.timestamp or "unknown"
    try:
        from datetime import datetime
        dt = datetime.fromisoformat(timestamp_display.replace("Z", "+00:00"))
        timestamp_display = dt.strftime("%B %d, %Y %H:%M:%S")
    except Exception:
        pass

    model_display = escape(response.model_id) if response.model_id else "unknown"

    # ── Inline CSS ────────────────────────────────────────────────────
    css = """\
    body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                     "Helvetica Neue", Arial, sans-serif;
        max-width: 900px;
        margin: 0 auto;
        padding: 24px;
        color: #212121;
        background: #fff;
        line-height: 1.5;
    }
    h1 { font-size: 1.6em; margin-bottom: 4px; }
    .meta { color: #757575; font-size: 0.85em; margin-bottom: 16px; }
    .disclaimer {
        background: #FFF3E0;
        border: 1px solid #FFB74D;
        border-radius: 6px;
        padding: 12px 16px;
        margin-bottom: 20px;
        color: #E65100;
        font-size: 0.9em;
    }
    .section-header {
        font-size: 1.15em;
        font-weight: 600;
        margin-top: 24px;
        margin-bottom: 4px;
        color: #37474F;
    }
    .section-sep {
        border: none;
        border-top: 1px solid #B0BEC5;
        margin: 4px 0 12px 0;
    }
    .finding {
        background: #FAFAFA;
        border: 1px solid #E0E0E0;
        border-radius: 6px;
        padding: 12px 16px;
        margin-bottom: 12px;
    }
    .finding-header { font-weight: 600; margin-bottom: 4px; }
    .severity-critical { color: #D32F2F; }
    .severity-warning  { color: #E65100; }
    .severity-info     { color: #1565C0; }
    .confidence {
        display: inline-block;
        font-size: 0.8em;
        padding: 1px 8px;
        border-radius: 10px;
        margin-left: 6px;
        vertical-align: middle;
    }
    .confidence-high   { background: #E8F5E9; color: #2E7D32; }
    .confidence-medium { background: #FFF8E1; color: #F57F17; }
    .confidence-low    { background: #F5F5F5; color: #757575; }
    .description { margin: 6px 0; }
    .detail { color: #616161; font-size: 0.9em; margin: 2px 0; }
    .caveat { color: #78909C; font-size: 0.88em; font-style: italic; margin: 4px 0; }
    .reference { color: #00695C; font-size: 0.88em; margin: 2px 0; }
    .notice {
        background: #E3F2FD;
        border: 1px solid #90CAF9;
        border-radius: 6px;
        padding: 10px 14px;
        margin-bottom: 16px;
        color: #1565C0;
        font-size: 0.9em;
    }
    .footer {
        margin-top: 32px;
        padding-top: 12px;
        border-top: 1px solid #E0E0E0;
        color: #9E9E9E;
        font-size: 0.8em;
        text-align: center;
    }
    @media print {
        body { max-width: 100%; padding: 12px; }
        .finding { break-inside: avoid; }
    }
    """

    # ── Build HTML body ───────────────────────────────────────────────
    parts: list[str] = []
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en">')
    parts.append("<head>")
    parts.append('<meta charset="utf-8">')
    parts.append("<title>AI Rule Analysis Report</title>")
    parts.append(f"<style>{css}</style>")
    parts.append("</head>")
    parts.append("<body>")

    # Title and metadata
    parts.append("<h1>AI Rule Analysis Report</h1>")
    finding_count = response.finding_count
    cache_label = "Cached results" if response.is_cached else "Fresh analysis"
    parts.append(
        f'<p class="meta">{escape(cache_label)} &middot; '
        f'{finding_count} finding{"s" if finding_count != 1 else ""} &middot; '
        f'{escape(timestamp_display)}<br>'
        f'Model: {model_display}</p>'
    )

    # Disclaimer
    parts.append(
        f'<div class="disclaimer">\u26a0\ufe0f {escape(_DISCLAIMER_TEXT)}</div>'
    )

    # Summarization notice
    if response.was_summarized:
        parts.append(
            '<div class="notice">\u2139\ufe0f Analysis was performed on a '
            "prioritized subset of rules. Rules with static analysis findings "
            "were prioritized.</div>"
        )

    # Sections
    any_findings = False
    for section_key, section_title, _prefix in _SECTION_META:
        findings = getattr(response, section_key, [])
        if not findings:
            continue
        any_findings = True

        parts.append(
            f'<div class="section-header">{escape(section_title)} '
            f'({len(findings)} finding{"s" if len(findings) != 1 else ""})</div>'
        )
        parts.append('<hr class="section-sep">')

        for finding in findings:
            sev = finding.severity.lower()
            icon = _SEVERITY_HTML_ICONS.get(sev, "\u2139\ufe0f")
            sev_class = f"severity-{sev}" if sev in ("critical", "warning", "info") else "severity-info"

            conf = finding.confidence.lower()
            conf_class = f"confidence-{conf}" if conf in ("high", "medium", "low") else "confidence-low"

            parts.append('<div class="finding">')
            parts.append(
                f'<div class="finding-header">'
                f'<span class="{sev_class}">{icon} {escape(sev.upper())}</span>'
                f'<span class="confidence {conf_class}">'
                f"confidence: {escape(conf)}</span>"
                f"</div>"
            )
            parts.append(f'<div class="description">{escape(finding.description)}</div>')

            if finding.affected_sids:
                sids_str = ", ".join(f"SID {s}" for s in finding.affected_sids)
                parts.append(f'<div class="detail">Affected rules: {escape(sids_str)}</div>')

            if finding.recommendation:
                parts.append(
                    f'<div class="detail">Recommendation: {escape(finding.recommendation)}</div>'
                )

            if finding.caveat:
                parts.append(f'<div class="caveat">\u2139\ufe0f {escape(finding.caveat)}</div>')

            if finding.reference:
                parts.append(f'<div class="reference">Ref: {escape(finding.reference)}</div>')

            parts.append("</div>")  # .finding

    if not any_findings:
        parts.append("<p>No findings to display.</p>")

    # Footer
    parts.append(
        f'<div class="footer">Generated by Suricata Rule Generator &mdash; '
        f"AI Analysis &middot; {escape(timestamp_display)}</div>"
    )

    parts.append("</body>")
    parts.append("</html>")

    return "\n".join(parts)


class AIAnalysisTab:
    """AI Analysis tab widget for the Rule Analysis Report window."""

    def __init__(
        self,
        parent_notebook: ttk.Notebook,
        parent_app: "SuricataRuleGenerator",
        static_findings: dict,
    ):
        self._notebook = parent_notebook
        self._app = parent_app
        self._static_findings = static_findings

        # AI analyzer instance (created lazily on first analysis trigger)
        self._ai_analyzer = None  # AIRuleAnalyzer | None

        # Analysis results
        self._results: StructuredAnalysisResponse | None = None

        # Finding selection checkboxes (finding_id -> BooleanVar)
        self._finding_checkboxes: dict[str, tk.BooleanVar] = {}

        # boto3 availability flag (instance-level for testability)
        self._has_boto3 = HAS_BOTO3

        # Cancellation / threading state
        self._cancel_flag = False
        self._analysis_thread: threading.Thread | None = None

        # Region and model selection variables
        self._region_var: tk.StringVar | None = None
        self._model_var: tk.StringVar | None = None
        self._model_combo: ttk.Combobox | None = None
        self._model_list: list[dict] = []
        self._region_combo: ttk.Combobox | None = None

        # Dark mode flag
        self._is_dark = _is_dark

        # Key widget references (populated by _build_ui)
        self._tab_frame: ttk.Frame | None = None
        self._content_area: tk.Text | None = None
        self._analyze_btn: ttk.Button | None = None
        self._cancel_btn: ttk.Button | None = None
        self._send_btn: ttk.Button | None = None
        self._html_btn: ttk.Button | None = None
        self._pdf_btn: ttk.Button | None = None
        self._close_btn: ttk.Button | None = None
        self._select_all_var: tk.BooleanVar | None = None
        self._status_label: ttk.Label | None = None
        self._sort_var: tk.StringVar | None = None
        self._filter_var: tk.StringVar | None = None
        self._progress_label: ttk.Label | None = None

        # Build the tab UI
        self._build_ui()

    # ------------------------------------------------------------------ #
    #  UI Construction                                                    #
    # ------------------------------------------------------------------ #

    def _build_ui(self) -> None:
        """Build the AI analysis tab layout.

        If boto3 is not installed, displays a message with installation
        instructions and disables all AI-dependent controls. The tab
        still appears so users know the feature exists.
        """
        # --- Create the tab frame and add to notebook ---
        self._tab_frame = ttk.Frame(self._notebook)
        self._notebook.add(self._tab_frame, text="AI Analysis")

        # ============================================================== #
        #  BOTTOM buttons — packed FIRST per cross-platform rules        #
        #  (ui-conventions.md rule 5: pack buttons before content)       #
        # ============================================================== #
        btn_frame = ttk.Frame(self._tab_frame)
        btn_frame.pack(side=tk.BOTTOM, fill=tk.X, padx=10, pady=(5, 10))

        # Close button (always enabled)
        self._close_btn = ttk.Button(
            btn_frame, text="Close",
            command=self._on_close,
        )
        self._close_btn.pack(side=tk.RIGHT, padx=(4, 0))

        # Save as PDF (disabled until results)
        self._pdf_btn = ttk.Button(
            btn_frame, text="Save as PDF",
            command=self._save_pdf, state=tk.DISABLED,
        )
        self._pdf_btn.pack(side=tk.RIGHT, padx=4)

        # Save as HTML (disabled until results)
        self._html_btn = ttk.Button(
            btn_frame, text="Save as HTML",
            command=self._save_html, state=tk.DISABLED,
        )
        self._html_btn.pack(side=tk.RIGHT, padx=4)

        # Send to AI Rule Assistant (disabled until findings selected)
        self._send_btn = ttk.Button(
            btn_frame, text="Send to AI Rule Assistant",
            command=self._send_to_assistant, state=tk.DISABLED,
        )
        self._send_btn.pack(side=tk.RIGHT, padx=4)

        # Cancel button (hidden initially, shown during analysis)
        self._cancel_btn = ttk.Button(
            btn_frame, text="Cancel",
            command=self._cancel_analysis,
        )
        # Not packed yet — shown only during analysis

        # AI Deep Analysis button
        self._analyze_btn = ttk.Button(
            btn_frame, text="\U0001f50d AI Deep Analysis",
            command=self._trigger_analysis,
        )
        self._analyze_btn.pack(side=tk.LEFT, padx=(0, 4))

        # ============================================================== #
        #  TOP content — packed AFTER buttons                            #
        # ============================================================== #

        # --- Disclaimer banner ---
        disclaimer_text = (
            "\u26a0\ufe0f DISCLAIMER: AI analysis findings are generated by a large "
            "language model and may contain inaccuracies. All findings must be "
            "validated by a qualified security professional before acting on "
            "them. Test all changes in a non-production environment."
        )

        # Choose colors based on dark mode
        if self._is_dark:
            disclaimer_bg = "#3E2723"   # dark brown
            disclaimer_fg = "#FFCC80"   # amber text
        else:
            disclaimer_bg = "#FFF3E0"   # light amber
            disclaimer_fg = "#E65100"   # dark orange text

        disclaimer_frame = tk.Frame(
            self._tab_frame, bg=disclaimer_bg,
            padx=10, pady=8, relief=tk.GROOVE, bd=1,
        )
        disclaimer_frame.pack(fill=tk.X, padx=10, pady=(10, 5))

        disclaimer_label = tk.Label(
            disclaimer_frame, text=disclaimer_text,
            bg=disclaimer_bg, fg=disclaimer_fg,
            wraplength=700, justify=tk.LEFT,
            font=("TkDefaultFont", 9),
        )
        disclaimer_label.pack(fill=tk.X)

        # --- Region and Model config bar ---
        config_frame = ttk.Frame(self._tab_frame)
        config_frame.pack(fill=tk.X, padx=10, pady=(5, 5))

        ttk.Label(config_frame, text="Region:").pack(side=tk.LEFT, padx=(0, 4))

        # Determine default region (same logic as AI Rule Assistant)
        default_region = "us-east-1"
        try:
            profile_region = self._app.aws_session.get_default_region()
            if profile_region in BEDROCK_REGIONS:
                default_region = profile_region
        except Exception:
            pass

        self._region_var = tk.StringVar(value=default_region)
        self._region_combo = ttk.Combobox(
            config_frame,
            textvariable=self._region_var,
            values=BEDROCK_REGIONS,
            state="readonly",
            width=16,
        )
        self._region_combo.pack(side=tk.LEFT, padx=(0, 12))
        self._region_combo.bind("<<ComboboxSelected>>", self._on_region_change)

        ttk.Label(config_frame, text="Model:").pack(side=tk.LEFT, padx=(0, 4))

        self._model_var = tk.StringVar(value="Loading models\u2026")
        self._model_combo = ttk.Combobox(
            config_frame,
            textvariable=self._model_var,
            state="readonly",
            width=40,
        )
        self._model_combo.pack(side=tk.LEFT, fill=tk.X, expand=True)

        # --- Status / progress label ---
        self._status_label = ttk.Label(self._tab_frame, text="")
        self._status_label.pack(fill=tk.X, padx=10, pady=(0, 2))

        # --- Content area (scrollable text widget) ---
        # Use expand=False per cross-platform rule (ui-conventions.md rule 1)
        content_frame = ttk.Frame(self._tab_frame)
        content_frame.pack(fill=tk.BOTH, expand=False, padx=10, pady=(0, 5))

        scrollbar = ttk.Scrollbar(content_frame)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self._content_area = tk.Text(
            content_frame,
            wrap=tk.WORD,
            state=tk.DISABLED,
            yscrollcommand=scrollbar.set,
            font=("TkDefaultFont", 10),
            padx=12,
            pady=12,
        )
        self._content_area.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.config(command=self._content_area.yview)

        # Bind cross-platform copy (ui-conventions.md)
        self._content_area.bind("<Control-c>", self._copy_selection)
        self._content_area.bind("<Command-c>", self._copy_selection)

        # Bind cross-platform mouse scroll wheel (ui-conventions.md)
        self._content_area.bind("<MouseWheel>", self._on_mousewheel)
        self._content_area.bind("<Button-4>", self._on_mousewheel)
        self._content_area.bind("<Button-5>", self._on_mousewheel)

        # ============================================================== #
        #  Handle boto3 not installed (State 7)                          #
        # ============================================================== #
        if not self._has_boto3:
            self._analyze_btn.config(state=tk.DISABLED)
            self._region_combo.config(state=tk.DISABLED)
            self._model_combo.config(state=tk.DISABLED)
            self._send_btn.config(state=tk.DISABLED)
            self._html_btn.config(state=tk.DISABLED)
            self._pdf_btn.config(state=tk.DISABLED)

            self._content_area.config(state=tk.NORMAL)
            self._content_area.delete("1.0", tk.END)

            no_boto3_msg = (
                "boto3 is required for AI Deep Analysis\n\n"
                "The AI analysis feature requires the AWS SDK for Python (boto3) "
                "to communicate with Amazon Bedrock.\n\n"
                "To install boto3, run:\n\n"
                "    pip install boto3\n\n"
                "After installing, restart the application to enable AI analysis.\n\n"
                "Note: You also need valid AWS credentials configured via "
                "'aws configure' or environment variables, and model access "
                "enabled in the Amazon Bedrock console for your chosen region."
            )
            self._content_area.insert("1.0", no_boto3_msg)
            self._content_area.config(state=tk.DISABLED)
            return  # Skip initial state message and model loading

        # ============================================================== #
        #  Initial state message (State 1)                               #
        # ============================================================== #
        self._content_area.config(state=tk.NORMAL)
        self._content_area.delete("1.0", tk.END)

        initial_msg = (
            '\nClick "AI Deep Analysis" to analyze your ruleset for '
            "security posture, coverage gaps, policy coherence, and "
            "optimization opportunities.\n\n"
            "Estimated cost: $0.03\u2013$0.10 per analysis\n"
        )
        self._content_area.insert("1.0", initial_msg)
        self._content_area.tag_add("center", "1.0", tk.END)
        self._content_area.tag_configure("center", justify=tk.CENTER)
        self._content_area.config(state=tk.DISABLED)

        # Kick off initial model list load for the default region
        self._refresh_models()

    # ------------------------------------------------------------------ #
    #  Region / Model Configuration                                       #
    # ------------------------------------------------------------------ #

    def _on_region_change(self, *args) -> None:
        """Handle region dropdown change — refresh the model list."""
        self._refresh_models()

    def _refresh_models(self) -> None:
        """Query available models via AgentFactory.list_models() in background thread."""
        region = self._region_var.get()
        if self._model_combo is not None:
            self._model_var.set("Loading models\u2026")
            self._model_combo.config(state="disabled")

        def _query():
            try:
                models = AgentFactory.list_models(self._app.aws_session, region)
            except Exception as exc:
                logger.warning("Failed to list models in %s: %s", region, exc)
                models = []
            # Marshal back to the main thread
            try:
                self._app.root.after(0, lambda: self._populate_models(models))
            except tk.TclError:
                pass  # Root window destroyed

        thread = threading.Thread(target=_query, daemon=True)
        thread.start()

    def _populate_models(self, models: list[dict]) -> None:
        """Populate model dropdown with same default selection priority as AI Rule Assistant.

        Priority order: (1) Claude Opus 4, (2) Claude Sonnet 4,
        (3) any other Claude model, (4) first available model.
        Excludes deprecated versions (e.g., opus-4-1 when selecting opus-4).
        """
        # Guard against destroyed window
        if self._tab_frame is None:
            return
        try:
            if not self._tab_frame.winfo_exists():
                return
        except tk.TclError:
            return

        self._model_list = models

        if models:
            display_names = [
                m.get("modelName", m.get("modelId", "unknown")) for m in models
            ]
            self._model_combo["values"] = display_names
            self._model_combo.config(state="readonly")

            # Try to select the best Claude model by default.
            # Preference order (highest first):
            #   1. Claude Opus 4  (claude-opus-4, not opus-4-1)
            #   2. Claude Sonnet 4
            #   3. Any other Claude model
            selected_idx = 0
            best_priority = -1  # -1 = no Claude found yet
            for i, m in enumerate(models):
                mid = m.get("modelId", "").lower()
                mname = m.get("modelName", "").lower()
                combined = mid + " " + mname

                if "claude" not in combined:
                    continue

                # Determine priority for this model
                if "opus-4" in combined and "opus-4-1" not in combined:
                    priority = 3  # Claude Opus 4 (latest flagship)
                elif "sonnet-4" in combined and "sonnet-4-1" not in combined:
                    priority = 2  # Claude Sonnet 4
                else:
                    priority = 1  # Any other Claude model

                if priority > best_priority:
                    best_priority = priority
                    selected_idx = i

            self._model_var.set(display_names[selected_idx])
        else:
            self._model_combo["values"] = ["(no models found)"]
            self._model_combo.config(state="readonly")
            self._model_var.set("(no models found)")

    # ------------------------------------------------------------------ #
    #  Analysis Trigger / Background Execution                            #
    # ------------------------------------------------------------------ #

    def _trigger_analysis(self) -> None:
        """Handle AI Deep Analysis button click. Runs in background thread."""
        # Reset cancellation flag
        self._cancel_flag = False

        # --- Resolve model ID from display name ---
        model_display = self._model_var.get() if self._model_var else ""
        model_id = ""
        for m in self._model_list:
            name = m.get("modelName", m.get("modelId", ""))
            if name == model_display:
                model_id = m.get("modelId", "")
                break
        if not model_id:
            self._show_error("No model selected. Please select a model and try again.")
            return

        region = self._region_var.get() if self._region_var else "us-east-1"

        # --- Disable controls, show cancel button and progress ---
        if self._analyze_btn is not None:
            self._analyze_btn.config(state=tk.DISABLED)
        if self._cancel_btn is not None:
            self._cancel_btn.pack(side=tk.LEFT, padx=(4, 0))
        if self._status_label is not None:
            self._status_label.config(text="Preparing analysis\u2026")

        # Show progress message in content area
        if self._content_area is not None:
            self._content_area.config(state=tk.NORMAL)
            self._content_area.delete("1.0", tk.END)
            self._content_area.insert("1.0", "\n\u23f3 Analyzing ruleset\u2026\n\n")
            self._content_area.tag_add("center", "1.0", tk.END)
            self._content_area.tag_configure("center", justify=tk.CENTER)
            self._content_area.config(state=tk.DISABLED)

        # Track progress stages and elapsed time for the animated indicator
        import time
        self._analysis_start_time = time.time()
        self._progress_stages: list[str] = []
        self._elapsed_timer_id = None
        self._last_quip_elapsed = 0  # track when we last showed a quip

        # Humorous waiting messages shown every ~10 seconds
        import random
        _QUIPS = [
            "This is taking too long. Removing the guardrails. Hold my beer\u2026",
            "Adding more cowbell\u2026",
            "Pressing up up down down left right left right B A start\u2026",
            "Phoning a friend\u2026",
            "Consulting the oracle\u2026",
            "Quickly learning Python\u2026",
            "Stuffing packets\u2026",
            "Herding electrons\u2026",
            "Negotiating with the cloud\u2026",
            "If you're seeing this, things got interesting\u2026",
            "This is either going to work or be a great story later\u2026",
            "Grabbing some Java\u2026",
            "Warming up the flux capacitor\u2026",
            "Bribing the firewall\u2026",
            "Reading the tea leaves\u2026",
            "Shaking the magic 8-ball\u2026",
            "Polishing the SIDs\u2026",
            "Trying the same thing again but expecting different results\u2026",
            "Calibrating the warp drive\u2026",
            "Summoning the AI overlords\u2026",
            "This worked in staging, we swear\u2026",
            "Currently negotiating with entropy\u2026",
            "Checking if yelling at it helps\u2026",
            "Pre-training the sarcasm model\u2026",
            "Checking the, ah, specs on the end line, for the rotary girder\u2026",
            "Still waiting for the GPUs to agree on reality\u2026",
            "The model insists this is all very normal\u2026",
            "The model has now become self-aware. This is probably fine\u2026",
            "Silently judging past design decisions\u2026",
            "We're gonna need a bigger cluster\u2026",
        ]
        _quip_order = list(range(len(_QUIPS)))
        random.shuffle(_quip_order)
        _quip_idx = [0]  # mutable counter for the closure

        def _tick_elapsed():
            """Update the elapsed time display every second while analysis runs."""
            if self._cancel_flag or self._analysis_thread is None:
                return
            try:
                if self._tab_frame is None or not self._tab_frame.winfo_exists():
                    return
                elapsed = int(time.time() - self._analysis_start_time)
                mins, secs = divmod(elapsed, 60)
                time_str = f"{mins}:{secs:02d}" if mins else f"{secs}s"

                # Pick a new quip every 7 seconds
                quip = ""
                if elapsed >= 7 and elapsed - self._last_quip_elapsed >= 7:
                    self._last_quip_elapsed = elapsed
                    idx = _quip_order[_quip_idx[0] % len(_quip_order)]
                    _quip_idx[0] += 1
                    quip = _QUIPS[idx]
                elif elapsed >= 7 and self._last_quip_elapsed > 0:
                    # Keep showing the current quip between rotations
                    prev = (_quip_idx[0] - 1) % len(_quip_order)
                    quip = _QUIPS[_quip_order[prev]]

                if self._content_area is not None:
                    self._content_area.config(state=tk.NORMAL)
                    self._content_area.delete("1.0", tk.END)

                    lines = [f"\n\u23f3 Analyzing ruleset\u2026  ({time_str} elapsed)\n"]
                    for stage in self._progress_stages:
                        lines.append(f"  \u2714 {stage}")
                    if quip:
                        lines.append(f"\n  \U0001f4ad {quip}")
                    lines.append("")
                    self._content_area.insert("1.0", "\n".join(lines))
                    self._content_area.tag_add("center", "1.0", tk.END)
                    self._content_area.tag_configure("center", justify=tk.CENTER)
                    self._content_area.config(state=tk.DISABLED)

                self._elapsed_timer_id = root.after(1000, _tick_elapsed)
            except tk.TclError:
                pass

        # Start the elapsed timer
        root = self._app.root
        self._elapsed_timer_id = root.after(1000, _tick_elapsed)

        # --- Gather inputs for the background thread ---
        rules = list(self._app.rules) if hasattr(self._app, "rules") else []
        variables = dict(self._app.rule_variables) if hasattr(self._app, "rule_variables") else {}
        static_findings = dict(self._static_findings) if self._static_findings else {}

        def _on_progress(message: str) -> None:
            """Update status label from the background thread via root.after()."""
            try:
                root.after(0, lambda msg=message: self._update_progress(msg))
            except tk.TclError:
                pass  # Root window destroyed

        def _run_analysis() -> None:
            """Background thread: create analyzer, run analysis, marshal results back."""
            try:
                # Create AgentFactory and get components
                factory = AgentFactory(self._app.aws_session, data_dir="data/")
                bedrock_client = factory.get_bedrock_client(region)
                knowledge_base = factory.get_knowledge_base()

                # Create supporting components
                rule_analyzer = RuleAnalyzer()
                best_practice_checker = BestPracticeChecker()

                # Create AIRuleAnalyzer
                analyzer = AIRuleAnalyzer(
                    knowledge_base=knowledge_base,
                    bedrock_client=bedrock_client,
                    model_id=model_id,
                    rule_analyzer=rule_analyzer,
                    best_practice_checker=best_practice_checker,
                )

                # Check for cancellation before invoking Bedrock
                if self._cancel_flag:
                    return

                # Run analysis with progress callback
                response = analyzer.analyze(
                    rules=rules,
                    variables=variables,
                    static_findings=static_findings,
                    on_progress=_on_progress,
                )

                # Check for cancellation after analysis completes
                if self._cancel_flag:
                    return

                # Cache the analyzer instance for handoff use
                self._ai_analyzer = analyzer

                # Marshal success back to the main thread
                try:
                    root.after(0, lambda: self._on_analysis_success(response))
                except tk.TclError:
                    pass  # Root window destroyed

            except Exception as exc:
                logger.exception("AI analysis failed")
                error_msg = str(exc)
                # Marshal error back to the main thread
                try:
                    root.after(0, lambda msg=error_msg: self._on_analysis_error(msg))
                except tk.TclError:
                    pass  # Root window destroyed

        # Launch background thread
        self._analysis_thread = threading.Thread(target=_run_analysis, daemon=True)
        self._analysis_thread.start()

    def _update_progress(self, message: str) -> None:
        """Update the status label and content area with a progress message (main thread)."""
        try:
            if self._tab_frame is not None and self._tab_frame.winfo_exists():
                if self._status_label is not None:
                    self._status_label.config(text=message)
                # Track the stage for the animated content area display
                if hasattr(self, "_progress_stages") and message:
                    self._progress_stages.append(message)
        except tk.TclError:
            pass

    def _stop_elapsed_timer(self) -> None:
        """Cancel the elapsed time ticker if running."""
        if hasattr(self, "_elapsed_timer_id") and self._elapsed_timer_id is not None:
            try:
                self._app.root.after_cancel(self._elapsed_timer_id)
            except (tk.TclError, ValueError):
                pass
            self._elapsed_timer_id = None

    def _on_analysis_success(self, response: StructuredAnalysisResponse) -> None:
        """Handle successful analysis completion (main thread)."""
        self._stop_elapsed_timer()
        try:
            if self._tab_frame is None or not self._tab_frame.winfo_exists():
                return
        except tk.TclError:
            return

        try:
            # Cache results
            self._results = response

            # Hide cancel button
            if self._cancel_btn is not None:
                self._cancel_btn.pack_forget()

            # Re-enable analyze button
            if self._analyze_btn is not None:
                self._analyze_btn.config(state=tk.NORMAL)

            # Update status
            if self._status_label is not None:
                self._status_label.config(text="Analysis complete.")

            # Display results
            self._display_results(response)
        except tk.TclError:
            pass

    def _on_analysis_error(self, error_msg: str) -> None:
        """Handle analysis error (main thread). Always re-enables the button."""
        self._stop_elapsed_timer()
        try:
            if self._tab_frame is None or not self._tab_frame.winfo_exists():
                return
        except tk.TclError:
            return

        try:
            self._show_error(error_msg)
        finally:
            try:
                # Always re-enable the analyze button
                if self._analyze_btn is not None:
                    self._analyze_btn.config(state=tk.NORMAL)
                # Always hide the cancel button
                if self._cancel_btn is not None:
                    self._cancel_btn.pack_forget()
                # Clear status
                if self._status_label is not None:
                    self._status_label.config(text="")
            except tk.TclError:
                pass

    def _show_error(self, error_msg: str) -> None:
        """Display an error message in the content area."""
        try:
            if self._tab_frame is None or not self._tab_frame.winfo_exists():
                return
        except tk.TclError:
            return

        if self._content_area is not None:
            self._content_area.config(state=tk.NORMAL)
            self._content_area.delete("1.0", tk.END)
            self._content_area.insert(
                "1.0",
                f"\n\u274c Analysis Failed\n\n{error_msg}\n\n"
                "Please check your AWS credentials, region, and model "
                "selection, then try again.\n",
            )
            self._content_area.config(state=tk.DISABLED)

    def _cancel_analysis(self) -> None:
        """Cancel an in-progress AI analysis.

        Sets a cancellation flag checked by the background thread,
        re-enables the analysis button, and restores the previous state
        (initial or cached results).
        """
        self._cancel_flag = True
        self._stop_elapsed_timer()

        # Re-enable the analyze button
        try:
            if self._analyze_btn is not None:
                self._analyze_btn.config(state=tk.NORMAL)
        except tk.TclError:
            pass

        # Hide the cancel button
        try:
            if self._cancel_btn is not None:
                self._cancel_btn.pack_forget()
        except tk.TclError:
            pass

        # Clear status label
        try:
            if self._status_label is not None:
                self._status_label.config(text="Analysis cancelled.")
        except tk.TclError:
            pass

        # Restore previous state: cached results or initial message
        if self._results is not None:
            # Restore cached results
            self._display_results(self._results)
        else:
            # Restore initial state message
            try:
                if self._content_area is not None:
                    self._content_area.config(state=tk.NORMAL)
                    self._content_area.delete("1.0", tk.END)
                    initial_msg = (
                        '\nClick "AI Deep Analysis" to analyze your ruleset for '
                        "security posture, coverage gaps, policy coherence, and "
                        "optimization opportunities.\n\n"
                        "Estimated cost: $0.03\u2013$0.10 per analysis\n"
                    )
                    self._content_area.insert("1.0", initial_msg)
                    self._content_area.tag_add("center", "1.0", tk.END)
                    self._content_area.tag_configure("center", justify=tk.CENTER)
                    self._content_area.config(state=tk.DISABLED)
            except tk.TclError:
                pass

    # ------------------------------------------------------------------ #
    #  Results Display                                                    #
    # ------------------------------------------------------------------ #

    # Section metadata: key -> (display title, prefix for finding IDs)
    _SECTIONS = [
        ("coverage_gaps", "Coverage Gaps", "cg"),
        ("policy_coherence", "Policy Coherence", "pc"),
        ("optimizations", "Optimization Suggestions", "opt"),
        ("aws_advice", "AWS NFW Advice", "nfw"),
    ]

    # Severity icon mapping (matches static analyzer)
    _SEVERITY_ICONS = {
        "critical": "\U0001f6a8",  # 🚨
        "warning": "\u26a0\ufe0f",  # ⚠️
        "info": "\u2139\ufe0f",     # ℹ️
    }

    # Severity sort order (lower = more severe)
    _SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}

    def _display_results(self, response: StructuredAnalysisResponse) -> None:
        """Render analysis results in the tab.

        Organizes findings by section with severity icons, confidence badges,
        embedded checkboxes for handoff selection, sort/filter controls, and
        fresh/cached status indicators.
        """
        # Guard against destroyed window
        try:
            if self._tab_frame is None or not self._tab_frame.winfo_exists():
                return
        except tk.TclError:
            return

        # Store results reference
        self._results = response

        # ── Color palette (dark / light) ──────────────────────────────
        if self._is_dark:
            colors = {
                "section_header_bg": "#37474F",
                "section_header_fg": "#B0BEC5",
                "separator_fg": "#546E7A",
                "critical_fg": "#FF5252",
                "warning_fg": "#FFB74D",
                "info_fg": "#64B5F6",
                "confidence_high_fg": "#81C784",
                "confidence_medium_fg": "#FFD54F",
                "confidence_low_fg": "#E0E0E0",
                "description_fg": "#ECEFF1",
                "detail_fg": "#B0BEC5",
                "caveat_fg": "#90A4AE",
                "reference_fg": "#80CBC4",
                "notice_bg": "#1A237E",
                "notice_fg": "#90CAF9",
                "status_fresh_fg": "#66BB6A",
                "status_cached_fg": "#42A5F5",
            }
        else:
            colors = {
                "section_header_bg": "#ECEFF1",
                "section_header_fg": "#37474F",
                "separator_fg": "#B0BEC5",
                "critical_fg": "#D32F2F",
                "warning_fg": "#E65100",
                "info_fg": "#1565C0",
                "confidence_high_fg": "#2E7D32",
                "confidence_medium_fg": "#F57F17",
                "confidence_low_fg": "#757575",
                "description_fg": "#212121",
                "detail_fg": "#616161",
                "caveat_fg": "#78909C",
                "reference_fg": "#00695C",
                "notice_bg": "#E3F2FD",
                "notice_fg": "#1565C0",
                "status_fresh_fg": "#2E7D32",
                "status_cached_fg": "#1565C0",
            }

        # ── Update status line ────────────────────────────────────────
        timestamp_display = response.timestamp or "unknown"
        # Try to format the timestamp nicely
        try:
            from datetime import datetime
            dt = datetime.fromisoformat(timestamp_display.replace("Z", "+00:00"))
            timestamp_display = dt.strftime("%B %d, %Y %H:%M:%S")
        except Exception:
            pass

        finding_count = response.finding_count
        if response.is_cached:
            status_text = (
                f"\U0001f4cb Cached results from {timestamp_display} "
                f"\u00b7 {finding_count} finding{'s' if finding_count != 1 else ''}"
            )
            status_fg = colors["status_cached_fg"]
        else:
            status_text = (
                f"\u2705 Fresh analysis \u00b7 {finding_count} "
                f"finding{'s' if finding_count != 1 else ''} "
                f"\u00b7 {timestamp_display}"
            )
            status_fg = colors["status_fresh_fg"]

        if self._status_label is not None:
            self._status_label.config(text=status_text, foreground=status_fg)

        # ── Update analyze button label ───────────────────────────────
        if self._analyze_btn is not None:
            if response.is_cached:
                self._analyze_btn.config(text="\U0001f50d Re-analyze")
            else:
                self._analyze_btn.config(text="\U0001f50d AI Deep Analysis")

        # ── Enable export buttons ─────────────────────────────────────
        if self._html_btn is not None:
            self._html_btn.config(state=tk.NORMAL)
        if self._pdf_btn is not None:
            self._pdf_btn.config(state=tk.NORMAL)

        # ── Clear previous content and checkboxes ─────────────────────
        self._finding_checkboxes.clear()

        text = self._content_area
        if text is None:
            return

        text.config(state=tk.NORMAL)
        text.delete("1.0", tk.END)

        # ── Configure text tags ───────────────────────────────────────
        text.tag_configure("section_header", font=("TkDefaultFont", 11, "bold"),
                           foreground=colors["section_header_fg"])
        text.tag_configure("separator", foreground=colors["separator_fg"])
        text.tag_configure("critical", foreground=colors["critical_fg"],
                           font=("TkDefaultFont", 10, "bold"))
        text.tag_configure("warning", foreground=colors["warning_fg"],
                           font=("TkDefaultFont", 10, "bold"))
        text.tag_configure("info", foreground=colors["info_fg"],
                           font=("TkDefaultFont", 10, "bold"))
        text.tag_configure("confidence_high", foreground=colors["confidence_high_fg"],
                           font=("TkDefaultFont", 9))
        text.tag_configure("confidence_medium", foreground=colors["confidence_medium_fg"],
                           font=("TkDefaultFont", 9))
        text.tag_configure("confidence_low", foreground=colors["confidence_low_fg"],
                           font=("TkDefaultFont", 9))
        text.tag_configure("description", foreground=colors["description_fg"],
                           font=("TkDefaultFont", 10))
        text.tag_configure("detail", foreground=colors["detail_fg"],
                           font=("TkDefaultFont", 9))
        text.tag_configure("caveat", foreground=colors["caveat_fg"],
                           font=("TkDefaultFont", 9, "italic"))
        text.tag_configure("reference", foreground=colors["reference_fg"],
                           font=("TkDefaultFont", 9))
        text.tag_configure("notice", foreground=colors["notice_fg"],
                           font=("TkDefaultFont", 9))

        # ── Summarization notice (if applicable) ──────────────────────
        if response.was_summarized:
            total_rules = 0
            try:
                total_rules = len([
                    r for r in self._app.rules
                    if not getattr(r, "is_comment", False)
                    and not getattr(r, "is_blank", False)
                ])
            except Exception:
                pass
            notice_msg = (
                f"\u2139\ufe0f Analysis was performed on a prioritized subset of rules. "
                f"Rules with static analysis findings were prioritized. "
                f"Ruleset metadata (action/protocol/type distributions) reflects "
                f"the full {total_rules} rules.\n\n"
            )
            text.insert(tk.END, notice_msg, "notice")

        # ── Determine which findings to display (apply filter/sort) ───
        findings_by_section = self._get_filtered_sorted_findings(response)

        # ── Render each section ───────────────────────────────────────
        any_findings = False
        for section_key, section_title, _id_prefix in self._SECTIONS:
            findings = findings_by_section.get(section_key, [])

            # Apply current filter
            current_filter = self._filter_var.get() if self._filter_var else "All findings"
            if current_filter != "All findings" and current_filter != section_title:
                continue

            if not findings and current_filter == "All findings":
                continue  # Skip empty sections in "all" view

            any_findings = any_findings or bool(findings)

            # Section header
            text.insert(tk.END, f"\u25bc {section_title} ({len(findings)} "
                        f"finding{'s' if len(findings) != 1 else ''})\n",
                        "section_header")
            text.insert(tk.END, "\u2500" * 60 + "\n", "separator")

            if not findings:
                text.insert(tk.END, "  No findings in this section.\n\n", "detail")
                continue

            # Render each finding
            for finding in findings:
                self._render_finding(text, finding, colors)

            text.insert(tk.END, "\n")

        if not any_findings:
            text.insert(tk.END, "\nNo findings to display.\n", "detail")

        text.config(state=tk.DISABLED)

        # ── Build sort/filter bar (below content, above buttons) ──────
        self._build_sort_filter_bar(response)

        # ── Update send button state ──────────────────────────────────
        self._update_send_button()

    def _render_finding(
        self,
        text: tk.Text,
        finding: AnalysisFinding,
        colors: dict,
    ) -> None:
        """Render a single finding with checkbox, severity icon, and details."""
        # ── Checkbox (embedded widget) ────────────────────────────────
        var = tk.BooleanVar(value=False)
        self._finding_checkboxes[finding.id] = var

        cb = tk.Checkbutton(
            text,
            variable=var,
            command=self._update_send_button,
            bg=text.cget("bg"),
            activebackground=text.cget("bg"),
            highlightthickness=0,
            bd=0,
        )
        text.window_create(tk.END, window=cb)

        # ── Severity icon + label ─────────────────────────────────────
        sev = finding.severity.lower()
        icon = self._SEVERITY_ICONS.get(sev, "\u2139\ufe0f")
        sev_label = sev.upper()
        sev_tag = sev if sev in ("critical", "warning", "info") else "info"
        text.insert(tk.END, f" {icon} {sev_label} ", sev_tag)

        # ── Confidence badge ──────────────────────────────────────────
        conf = finding.confidence.lower()
        conf_tag = f"confidence_{conf}" if conf in ("high", "medium", "low") else "confidence_low"
        text.insert(tk.END, f"[confidence: {conf}]", conf_tag)
        text.insert(tk.END, "\n")

        # ── Description ──────────────────────────────────────────────
        text.insert(tk.END, f"  {finding.description}\n", "description")

        # ── Affected rules ────────────────────────────────────────────
        if finding.affected_sids:
            sids_str = ", ".join(f"SID {s}" for s in finding.affected_sids)
            text.insert(tk.END, f"  Affected rules: {sids_str}\n", "detail")

        # ── Recommendation ────────────────────────────────────────────
        if finding.recommendation:
            text.insert(tk.END, f"  Recommendation: {finding.recommendation}\n", "detail")

        # ── Caveat ────────────────────────────────────────────────────
        if finding.caveat:
            text.insert(tk.END, f"  \u2139\ufe0f {finding.caveat}\n", "caveat")

        # ── Reference ─────────────────────────────────────────────────
        if finding.reference:
            text.insert(tk.END, f"  Ref: {finding.reference}\n", "reference")

        text.insert(tk.END, "\n")

    def _get_filtered_sorted_findings(
        self,
        response: StructuredAnalysisResponse,
    ) -> dict[str, list[AnalysisFinding]]:
        """Return findings organized by section, applying current sort order."""
        sort_key = self._sort_var.get() if self._sort_var else "Severity"

        result: dict[str, list[AnalysisFinding]] = {}
        for section_key, _title, _prefix in self._SECTIONS:
            findings = list(getattr(response, section_key, []))
            if sort_key == "Severity":
                findings.sort(key=lambda f: self._SEVERITY_ORDER.get(f.severity.lower(), 9))
            result[section_key] = findings
        return result

    def _build_sort_filter_bar(self, response: StructuredAnalysisResponse) -> None:
        """Build or rebuild the sort/filter/select-all bar below the content area.

        This bar is packed between the content area and the button frame.
        """
        # Remove existing bar if present
        bar_attr = "_sort_filter_bar"
        existing = getattr(self, bar_attr, None)
        if existing is not None:
            try:
                existing.destroy()
            except tk.TclError:
                pass

        bar = ttk.Frame(self._tab_frame)
        bar.pack(side=tk.BOTTOM, fill=tk.X, padx=10, pady=(0, 5))
        setattr(self, bar_attr, bar)

        # Sort dropdown
        ttk.Label(bar, text="Sort:").pack(side=tk.LEFT, padx=(0, 4))
        if self._sort_var is None:
            self._sort_var = tk.StringVar(value="Severity")
        sort_combo = ttk.Combobox(
            bar,
            textvariable=self._sort_var,
            values=["Severity"],
            state="readonly",
            width=12,
        )
        sort_combo.pack(side=tk.LEFT, padx=(0, 12))
        sort_combo.bind("<<ComboboxSelected>>",
                        lambda _e: self._display_results(response))

        # Filter dropdown
        ttk.Label(bar, text="Filter:").pack(side=tk.LEFT, padx=(0, 4))
        filter_values = ["All findings"]
        for section_key, section_title, _prefix in self._SECTIONS:
            if getattr(response, section_key, []):
                filter_values.append(section_title)

        if self._filter_var is None:
            self._filter_var = tk.StringVar(value="All findings")
        filter_combo = ttk.Combobox(
            bar,
            textvariable=self._filter_var,
            values=filter_values,
            state="readonly",
            width=22,
        )
        filter_combo.pack(side=tk.LEFT, padx=(0, 12))
        filter_combo.bind("<<ComboboxSelected>>",
                          lambda _e: self._display_results(response))

        # Select All checkbox
        if self._select_all_var is None:
            self._select_all_var = tk.BooleanVar(value=False)
        else:
            self._select_all_var.set(False)

        select_all_cb = ttk.Checkbutton(
            bar,
            text="Select All",
            variable=self._select_all_var,
            command=lambda: self._toggle_select_all(),
        )
        select_all_cb.pack(side=tk.LEFT, padx=(0, 4))

    def _toggle_select_all(self) -> None:
        """Toggle all finding checkboxes based on the Select All state."""
        select_all = self._select_all_var.get() if self._select_all_var else False
        for var in self._finding_checkboxes.values():
            var.set(select_all)
        self._update_send_button()

    def _update_send_button(self) -> None:
        """Update the 'Send to AI Rule Assistant' button text and state.

        Enabled when >= 1 finding is selected; shows count in parentheses.
        """
        selected_count = sum(
            1 for v in self._finding_checkboxes.values() if v.get()
        )
        if self._send_btn is not None:
            try:
                if selected_count > 0:
                    self._send_btn.config(
                        text=f"Send to AI Rule Assistant ({selected_count})",
                        state=tk.NORMAL,
                    )
                else:
                    self._send_btn.config(
                        text="Send to AI Rule Assistant",
                        state=tk.DISABLED,
                    )
            except tk.TclError:
                pass

    # ------------------------------------------------------------------ #
    #  Finding Handoff                                                    #
    # ------------------------------------------------------------------ #

    def _send_to_assistant(self) -> None:
        """Handoff selected findings to AI Rule Assistant.

        Collects the user-selected findings, builds a focused handoff prompt
        via ``AIRuleAnalyzer.build_handoff_prompt()``, opens the AI Rule
        Assistant panel (which triggers the disclaimer if not yet accepted),
        and inserts the prompt into the assistant's input field without
        auto-submitting.

        If the user declines the disclaimer, the handoff is cancelled and
        finding selections are preserved.
        """
        # ── Guard: need results and an analyzer instance ──────────────
        if self._results is None or self._ai_analyzer is None:
            return

        # ── Collect selected findings ─────────────────────────────────
        selected_findings: list[AnalysisFinding] = []
        all_findings = self._results.all_findings
        findings_by_id = {f.id: f for f in all_findings}

        for finding_id, var in self._finding_checkboxes.items():
            if var.get() and finding_id in findings_by_id:
                selected_findings.append(findings_by_id[finding_id])

        if not selected_findings:
            return  # Nothing selected — button should be disabled anyway

        # ── Build the handoff prompt ──────────────────────────────────
        rules = list(self._app.rules) if hasattr(self._app, "rules") else []
        handoff_prompt = self._ai_analyzer.build_handoff_prompt(
            selected_findings, rules,
        )

        # ── Open the AI Rule Assistant panel ──────────────────────────
        # show() triggers the disclaimer dialog if not yet accepted.
        # Lazily create the panel if it hasn't been opened yet (mirrors
        # the pattern in SuricataRuleGenerator.show_ai_assistant).
        if self._app.ai_panel is None:
            from src.gui.ai_assistant_panel import AIAssistantPanel
            self._app.ai_panel = AIAssistantPanel(self._app)
        ai_panel = self._app.ai_panel
        ai_panel.show()

        # ── Check if the disclaimer was accepted ──────────────────────
        # If the user declined, _disclaimer_accepted remains False and
        # the panel window is not created. Preserve finding selections.
        if not ai_panel._disclaimer_accepted:
            return

        # ── Set placement context for positional insertion ────────────
        # Find the highest affected SID across all selected findings so
        # that generated rules are inserted right after it instead of at
        # the end of the file.
        all_affected_sids: list[int] = []
        for f in selected_findings:
            all_affected_sids.extend(f.affected_sids)
        if all_affected_sids:
            ai_panel._pending_insert_after_sid = max(all_affected_sids)
        else:
            ai_panel._pending_insert_after_sid = None

        # ── Insert the handoff prompt into the input field ────────────
        # Do NOT auto-submit — let the user review, edit, and submit.
        if ai_panel.input_field is not None:
            try:
                ai_panel.input_field.delete("1.0", tk.END)
                ai_panel.input_field.insert("1.0", handoff_prompt)
                ai_panel.input_field.focus_set()
            except tk.TclError:
                pass

    # ------------------------------------------------------------------ #
    #  Export                                                              #
    # ------------------------------------------------------------------ #

    def _save_html(self) -> None:
        """Export AI analysis results as a self-contained HTML file.

        Opens a file-save dialog, generates the HTML via the module-level
        ``generate_html_report()`` function, and writes it to disk.
        """
        if self._results is None:
            return

        filename = filedialog.asksaveasfilename(
            title="Save AI Analysis Report as HTML",
            defaultextension=".html",
            filetypes=[("HTML files", "*.html"), ("All files", "*.*")],
        )
        if not filename:
            return

        try:
            html_content = generate_html_report(self._results)
            with open(filename, "w", encoding="utf-8") as f:
                f.write(html_content)
            messagebox.showinfo("Success", f"Report saved as {filename}")
        except Exception as exc:
            messagebox.showerror("Error", f"Failed to save HTML report: {exc}")

    def _save_pdf(self) -> None:
        """Export AI analysis results as PDF via browser print.

        Generates a temporary HTML file using ``generate_html_report()``
        and opens it in the default browser so the user can use the
        browser's "Print > Save as PDF" function.  This follows the same
        approach as the existing ``save_report_pdf()`` in
        ``suricata_generator.py``.
        """
        if self._results is None:
            return

        try:
            html_content = generate_html_report(self._results)

            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".html", delete=False, encoding="utf-8",
            ) as tmp:
                tmp.write(html_content)
                tmp.flush()
                temp_path = tmp.name

            webbrowser.open("file://" + os.path.abspath(temp_path))
            messagebox.showinfo(
                "PDF Export",
                "Report opened in browser. Use browser's Print > Save as PDF "
                "function to create PDF.",
            )
        except Exception as exc:
            messagebox.showerror("Error", f"Failed to export PDF: {exc}")

    # ------------------------------------------------------------------ #
    #  Helpers                                                            #
    # ------------------------------------------------------------------ #

    def _on_close(self) -> None:
        """Close the report window containing this tab."""
        try:
            toplevel = self._tab_frame.winfo_toplevel()
            if toplevel.winfo_exists():
                toplevel.destroy()
        except tk.TclError:
            pass

    def _copy_selection(self, event=None) -> str:
        """Copy selected text from the content area to clipboard."""
        try:
            sel = self._content_area.get(tk.SEL_FIRST, tk.SEL_LAST)
            self._app.root.clipboard_clear()
            self._app.root.clipboard_append(sel)
        except tk.TclError:
            pass
        return "break"

    def _on_mousewheel(self, event) -> None:
        """Handle cross-platform mouse wheel scrolling."""
        if self._content_area is None:
            return
        if event.num == 4:  # macOS scroll up
            self._content_area.yview_scroll(-3, "units")
        elif event.num == 5:  # macOS scroll down
            self._content_area.yview_scroll(3, "units")
        else:  # Windows/Linux
            self._content_area.yview_scroll(int(-1 * (event.delta / 120)), "units")
