"""
Constants for Suricata Rule Generator

This module contains all application constants to avoid magic numbers
and strings scattered throughout the codebase.
"""

class SuricataConstants:
    """Core Suricata rule constants"""
    
    # SID validation
    SID_MIN = 1
    SID_MAX = 999999999
    
    # File size limits (10MB for rule files, 1MB for domain lists)  
    MAX_RULE_FILE_SIZE = 10 * 1024 * 1024  # 10MB
    MAX_DOMAIN_FILE_SIZE = 1 * 1024 * 1024  # 1MB
    MAX_HISTORY_FILE_SIZE = 5 * 1024 * 1024  # 5MB
    
    # Rule capacity settings
    CAPACITY_BUFFER = 100  # Buffer added to actual rule count for AWS exports
    
    # Network and port validation
    SUPPORTED_PROTOCOLS = ["dcerpc", "dhcp", "dns", "ftp", "http", "http2", "icmp", "ikev2", "imap", "ip", "krb5", "msn", "ntp", "quic", "smb", "smtp", "ssh", "tcp", "tftp", "tls", "udp"]
    SUPPORTED_ACTIONS = ["pass", "alert", "drop", "reject"]
    SUPPORTED_DIRECTIONS = ["->", "<>"]
    
    # Port ranges
    PORT_MIN = 1
    PORT_MAX = 65535
    
    # UI constants
    DEFAULT_WINDOW_WIDTH = 1220
    DEFAULT_WINDOW_HEIGHT = 800
    DIALOG_TIMEOUT = 30  # seconds
    
    # File extensions
    SURICATA_EXT = ".suricata"
    VARIABLES_EXT = ".var"
    HISTORY_EXT = ".history"
    
    # Network timeouts
    HTTP_TIMEOUT = 10  # seconds for AWS template fetching
    
    # Encoding
    DEFAULT_ENCODING = "utf-8"


class SecurityConstants:
    """Security-related constants and patterns"""
    
    # File size limits
    MAX_IMPORT_FILE_SIZE = 10 * 1024 * 1024  # 10MB
    
    # Dangerous patterns for input validation
    # Note: Patterns are intentionally minimal for Suricata rule context
    # Suricata rules legitimately use semicolons, parentheses, dollar signs, etc.
    DANGEROUS_PATTERNS = [
        r'<script[^>]*>',      # XSS script tags (unlikely in Suricata rules)
        r'<\?php',             # PHP tags (unlikely in Suricata rules)
        r'<%.*%>',             # ASP tags (unlikely in Suricata rules)
        r'[\x00-\x08\x0b\x0c\x0e-\x1f]',   # Null bytes and control characters (excluding \t, \n, \r)
    ]
    
    # Maximum lengths for various inputs
    # AWS Network Firewall allows up to 8,192 characters per Suricata rule
    # Setting component limits to 8,000 to allow headroom for rule structure
    MAX_MESSAGE_LENGTH = 8000
    MAX_CONTENT_LENGTH = 8000
    MAX_DOMAIN_LENGTH = 253  # RFC compliant domain length
    MAX_VARIABLE_NAME_LENGTH = 100
    MAX_VARIABLE_VALUE_LENGTH = 5000
    MAX_COMMENT_LENGTH = 8000
    
    # Allowed characters for various inputs
    SAFE_FILENAME_PATTERN = r'^[a-zA-Z0-9._\-]+$'
    DOMAIN_PATTERN = r'^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*$'
    
    # Rate limiting
    MAX_RULES_PER_IMPORT = 30000  # Maximum rules allowed in a single import (matches AWS stateful rules limit)
    MAX_DOMAINS_PER_IMPORT = 10000  # Maximum domains allowed in a single import


class UIConstants:
    """User interface constants"""
    
    # Colors for rule types
    COLORS = {
        'pass': '#2E7D32',      # Green
        'alert': '#1976D2',     # Blue  
        'drop': '#D32F2F',      # Red
        'reject': '#7B1FA2',    # Purple
        'comment': '#808080',   # Grey
        'search_highlight': '#FFFF00',  # Yellow
        'warning': '#FF6600',   # Orange
    }
    
    # Font settings
    DEFAULT_FONT = ("TkDefaultFont", 9)
    MONOSPACE_FONT = ("Consolas", 9)
    BOLD_FONT = ("TkDefaultFont", 9, "bold")
    
    # Dialog sizes
    DIALOG_SIZES = {
        'small': (300, 150),
        'medium': (500, 400), 
        'large': (700, 600),
        'xlarge': (900, 700),
    }
    
    # Status messages
    STATUS_MESSAGES = {
        'ready': 'Ready',
        'modified': 'Modified', 
        'saving': 'Saving...',
        'loading': 'Loading...',
        'analyzing': 'Analyzing rules...',
    }


class ExportConstants:
    """Export template constants"""
    
    # AWS resource names
    DEFAULT_RULE_GROUP_NAME = "suricata-generator-rg"
    DEFAULT_RULE_GROUP_DESCRIPTION = "Rule group created by Suricata Generator"
    
    # Template formats
    TERRAFORM_EXT = ".tf"
    CLOUDFORMATION_EXT = ".cft"
    HTML_EXT = ".html"
    PDF_EXT = ".pdf"
    
    # Export limits
    AWS_MAX_CAPACITY = 30000  # Maximum capacity for AWS Network Firewall rule groups
    
    # Template headers
    TERRAFORM_HEADER = '# Generated by Suricata Rule Generator'
    CLOUDFORMATION_HEADER = '"Description": "Generated by Suricata Rule Generator"'


class ValidationMessages:
    """Standardized validation error messages"""
    
    SID_RANGE = f"SID must be between {SuricataConstants.SID_MIN} and {SuricataConstants.SID_MAX}"
    SID_REQUIRED = "SID is required"
    SID_DUPLICATE = "SID {sid} is already in use. Please choose a different SID."
    
    NETWORK_INVALID = "Network field must be 'any', a variable starting with $ or @, a valid CIDR notation, or a Suricata group expression"
    NETWORK_GROUP_INVALID = "Network group must contain valid CIDR blocks, IP addresses, or variables separated by commas"
    NETWORK_NEGATION_INVALID = "Network negation must be followed by a valid network specification"
    NETWORK_EMPTY_GROUP = "Network group cannot be empty - groups must contain at least one network specification"
    NETWORK_EMPTY_NEGATION = "Network negation cannot be empty"
    
    PORT_INVALID = f"Port must be 'any', a variable, or a number between {SuricataConstants.PORT_MIN} and {SuricataConstants.PORT_MAX}"
    
    FILE_TOO_LARGE = "File size exceeds maximum allowed size of {max_size} MB"
    FILE_NOT_FOUND = "File not found: {filename}"
    FILE_PERMISSION_DENIED = "Permission denied accessing file: {filename}"
    FILE_ENCODING_ERROR = "File encoding error. Please ensure the file is saved in UTF-8 format."
    
    DANGEROUS_INPUT = "Input contains potentially dangerous characters or patterns"
    INPUT_TOO_LONG = "Input exceeds maximum allowed length of {max_length} characters"
    
    NETWORK_ERROR = "Network error: {error}"
    TIMEOUT_ERROR = "Operation timed out after {seconds} seconds"
