"""
Constants for Suricata Rule Generator

This module contains all application constants to avoid magic numbers
and strings scattered throughout the codebase.
"""

import re


class SuricataConstants:
    """Core Suricata rule constants"""
    
    # SID validation
    SID_MIN = 1
    SID_MAX = 4294967294  # AWS Network Firewall maximum SID value (validated in AWS console)
    
    # File size limits (10MB for rule files, 1MB for domain lists)  
    MAX_RULE_FILE_SIZE = 10 * 1024 * 1024  # 10MB
    MAX_DOMAIN_FILE_SIZE = 1 * 1024 * 1024  # 1MB
    MAX_HISTORY_FILE_SIZE = 5 * 1024 * 1024  # 5MB
    
    # Rule capacity settings
    CAPACITY_BUFFER = 100  # Buffer added to actual rule count for AWS exports
    
    # Network and port validation
    SUPPORTED_PROTOCOLS = ["dcerpc", "dhcp", "dns", "ftp", "http", "http2", "icmp", "ikev2", "imap", "ip", "krb5", "msn", "ntp", "quic", "smb", "smtp", "ssh", "tcp", "tftp", "tls", "udp"]
    SUPPORTED_ACTIONS = ["pass", "alert", "drop", "reject"]
    SUPPORTED_DIRECTIONS = ["->", "<>"]
    
    # Port ranges
    PORT_MIN = 1
    PORT_MAX = 65535
    
    # UI constants
    DEFAULT_WINDOW_WIDTH = 1220
    DEFAULT_WINDOW_HEIGHT = 800
    DIALOG_TIMEOUT = 30  # seconds
    
    # File extensions
    SURICATA_EXT = ".suricata"
    VARIABLES_EXT = ".var"
    HISTORY_EXT = ".history"
    
    # Network timeouts
    HTTP_TIMEOUT = 10  # seconds for AWS template fetching
    
    # Encoding
    DEFAULT_ENCODING = "utf-8"


class SecurityConstants:
    """Security-related constants and patterns"""
    
    # File size limits
    MAX_IMPORT_FILE_SIZE = 10 * 1024 * 1024  # 10MB
    
    # Dangerous patterns for input validation
    # Note: Patterns are intentionally minimal for Suricata rule context
    # Suricata rules legitimately use semicolons, parentheses, dollar signs, etc.
    DANGEROUS_PATTERNS = [
        r'<script[^>]*>',      # XSS script tags (unlikely in Suricata rules)
        r'<\?php',             # PHP tags (unlikely in Suricata rules)
        r'<%.*%>',             # ASP tags (unlikely in Suricata rules)
        r'[\x00-\x08\x0b\x0c\x0e-\x1f]',   # Null bytes and control characters (excluding \t, \n, \r)
    ]
    
    # Maximum lengths for various inputs
    # AWS Network Firewall allows up to 8,192 characters per Suricata rule
    # Setting component limits to 8,000 to allow headroom for rule structure
    MAX_MESSAGE_LENGTH = 8000
    MAX_CONTENT_LENGTH = 8000
    MAX_DOMAIN_LENGTH = 253  # RFC compliant domain length
    MAX_VARIABLE_NAME_LENGTH = 100
    MAX_VARIABLE_VALUE_LENGTH = 5000
    MAX_COMMENT_LENGTH = 8000
    
    # Allowed characters for various inputs
    SAFE_FILENAME_PATTERN = r'^[a-zA-Z0-9._\-]+$'
    DOMAIN_PATTERN = r'^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*$'
    
    # Rate limiting
    MAX_RULES_PER_IMPORT = 30000  # Maximum rules allowed in a single import (matches AWS stateful rules limit)
    MAX_DOMAINS_PER_IMPORT = 10000  # Maximum domains allowed in a single import


class UIConstants:
    """User interface constants"""
    
    # Colors for rule types
    COLORS = {
        'pass': '#2E7D32',      # Green
        'alert': '#1976D2',     # Blue  
        'drop': '#D32F2F',      # Red
        'reject': '#7B1FA2',    # Purple
        'comment': '#808080',   # Grey
        'search_highlight': '#FFFF00',  # Yellow
        'warning': '#FF6600',   # Orange
    }
    
    # Font settings
    DEFAULT_FONT = ("TkDefaultFont", 9)
    MONOSPACE_FONT = ("Consolas", 9)
    BOLD_FONT = ("TkDefaultFont", 9, "bold")
    
    # Dialog sizes
    DIALOG_SIZES = {
        'small': (300, 150),
        'medium': (500, 400), 
        'large': (700, 600),
        'xlarge': (900, 700),
    }
    
    # Status messages
    STATUS_MESSAGES = {
        'ready': 'Ready',
        'modified': 'Modified', 
        'saving': 'Saving...',
        'loading': 'Loading...',
        'analyzing': 'Analyzing rules...',
    }


class ExportConstants:
    """Export template constants"""
    
    # AWS resource names
    DEFAULT_RULE_GROUP_NAME = "suricata-generator-rg"
    DEFAULT_RULE_GROUP_DESCRIPTION = "Rule group created by Suricata Generator"
    
    # Template formats
    TERRAFORM_EXT = ".tf"
    CLOUDFORMATION_EXT = ".cft"
    HTML_EXT = ".html"
    PDF_EXT = ".pdf"
    
    # Export limits
    AWS_MAX_CAPACITY = 30000  # Maximum capacity for AWS Network Firewall rule groups
    
    # Template headers
    TERRAFORM_HEADER = '# Generated by Suricata Rule Generator'
    CLOUDFORMATION_HEADER = '"Description": "Generated by Suricata Rule Generator"'


class ValidationMessages:
    """Standardized validation error messages"""
    
    SID_RANGE = f"SID must be between {SuricataConstants.SID_MIN} and {SuricataConstants.SID_MAX}"
    SID_REQUIRED = "SID is required"
    SID_DUPLICATE = "SID {sid} is already in use. Please choose a different SID."
    
    NETWORK_INVALID = "Network field must be 'any', a variable starting with $ or @, a valid CIDR notation, or a Suricata group expression"
    NETWORK_GROUP_INVALID = "Network group must contain valid CIDR blocks, IP addresses, or variables separated by commas"
    NETWORK_NEGATION_INVALID = "Network negation must be followed by a valid network specification"
    NETWORK_EMPTY_GROUP = "Network group cannot be empty - groups must contain at least one network specification"
    NETWORK_EMPTY_NEGATION = "Network negation cannot be empty"
    
    PORT_INVALID = f"Port must be 'any', a variable, or a number between {SuricataConstants.PORT_MIN} and {SuricataConstants.PORT_MAX}"
    
    FILE_TOO_LARGE = "File size exceeds maximum allowed size of {max_size} MB"
    FILE_NOT_FOUND = "File not found: {filename}"
    FILE_PERMISSION_DENIED = "Permission denied accessing file: {filename}"
    FILE_ENCODING_ERROR = "File encoding error. Please ensure the file is saved in UTF-8 format."
    
    DANGEROUS_INPUT = "Input contains potentially dangerous characters or patterns"
    INPUT_TOO_LONG = "Input exceeds maximum allowed length of {max_length} characters"
    
    NETWORK_ERROR = "Network error: {error}"
    TIMEOUT_ERROR = "Operation timed out after {seconds} seconds"


# Bedrock-supported regions for AI feature region dropdowns
BEDROCK_REGIONS = [
    "us-east-1",
    "us-west-2",
    "eu-west-1",
    "ap-northeast-1",
    "ap-southeast-1",
]


# ---------------------------------------------------------------------------
# Reference-ARN classification (shared)
#
# Container associations use the same @ variable notation and the same
# AWS ReferenceSets.IPSetReferences block as traditional IP set references,
# so the only way to tell them apart from an ARN value is its shape. These
# patterns and helpers are the single source of truth used by import
# classification (R8), auto-detection reclassification (R12.6), and the
# non-blocking reference-value validation (R3, R15).
#
# All checks are shape-based and non-authoritative: malformed or non-ARN
# values classify as "reference" and drive soft warnings; AWS remains the
# authoritative validator at deploy time.
# ---------------------------------------------------------------------------

# Matches an AWS Network Firewall container-association ARN, e.g.
#   arn:aws:network-firewall:us-east-2:123456789012:container-association/ECSAZ1
# Case-insensitive and tolerant of surrounding whitespace (callers strip()).
# The partition segment is matched as arn:aws* (aws, aws-us-gov, aws-cn, ...).
CONTAINER_ASSOCIATION_ARN_RE = re.compile(
    r'^arn:aws[\w-]*:network-firewall:[^:]*:[^:]*:container-association/.+$',
    re.IGNORECASE,
)

# Matches any AWS ARN shape (arn:aws...:...). Used to recognize whether a
# traditional reference value at least looks like an ARN. Anything that is
# not a container association but matches this is treated as a reference.
REFERENCE_ARN_RE = re.compile(
    r'^arn:aws[\w-]*:.+$',
    re.IGNORECASE,
)


def classify_reference_arn(arn):
    """Classify an @ variable's ARN value as a container association or a reference.

    Returns "container" when the value matches the container-association ARN
    pattern, otherwise "reference". Malformed, empty, or non-ARN values
    classify as "reference" (they never raise); these drive the soft warnings
    in R3/R15 rather than hard-blocking. Used by import (R8), auto-detection
    reclassification (R12.6), and value validation (R3.3, R15).

    Args:
        arn: The ARN string to classify (may be None or non-string).

    Returns:
        "container" or "reference".
    """
    if not isinstance(arn, str):
        return "reference"
    if CONTAINER_ASSOCIATION_ARN_RE.match(arn.strip()):
        return "container"
    return "reference"


def looks_like_valid_reference_arn(arn):
    """Return True when a value looks like a plausible AWS reference ARN.

    Used by the non-blocking R15 traditional-reference value validation to
    decide whether to soft-warn. Recognizes both container-association ARNs
    and other arn:aws... shapes; returns False for empty, non-string, or
    garbage values. This is a shape check only and is never authoritative;
    AWS validates the ARN at deploy time.

    Args:
        arn: The value to check (may be None or non-string).

    Returns:
        True if the value resembles an AWS ARN, False otherwise.
    """
    if not isinstance(arn, str):
        return False
    return bool(REFERENCE_ARN_RE.match(arn.strip()))


# ---------------------------------------------------------------------------
# Cluster-ARN classification (Container Association Manager)
#
# When a user selects or manually enters an ECS/EKS cluster for a container
# association's monitoring configuration, the tool sanity-checks the ARN's
# shape so it can warn (never hard-block) before AWS rejects a bad value.
# These helpers also extract the Region and account segments so the create
# flow can warn when a manually entered cluster ARN is in a different Region
# or account than the association being created (R7a.3).
#
# All checks are shape-based and non-authoritative: malformed values simply
# fail the shape test and drive soft warnings; AWS remains the authoritative
# validator at create/update time.
# ---------------------------------------------------------------------------

# Matches an ECS cluster ARN, e.g.
#   arn:aws:ecs:us-east-2:123456789012:cluster/my-cluster
# Case-insensitive; partition matched as arn:aws* (aws, aws-us-gov, aws-cn).
ECS_CLUSTER_ARN_RE = re.compile(
    r'^arn:aws[\w-]*:ecs:[^:]*:[^:]*:cluster/.+$',
    re.IGNORECASE,
)

# Matches an EKS cluster ARN, e.g.
#   arn:aws:eks:us-east-2:123456789012:cluster/my-cluster
EKS_CLUSTER_ARN_RE = re.compile(
    r'^arn:aws[\w-]*:eks:[^:]*:[^:]*:cluster/.+$',
    re.IGNORECASE,
)


def looks_like_cluster_arn(arn, container_type):
    """Return True when arn matches the cluster ARN shape for the given type.

    Shape-only, non-authoritative check used to soft-warn when a manually
    entered cluster ARN does not look like a cluster ARN of the association's
    fixed type (R7a.4). Never raises: empty/non-string/garbage returns False.

    Args:
        arn: The ARN string to check (may be None or non-string).
        container_type: "ECS" or "EKS" (case-insensitive).

    Returns:
        True if arn matches the expected cluster ARN shape for container_type.
    """
    if not isinstance(arn, str) or not isinstance(container_type, str):
        return False
    arn = arn.strip()
    ctype = container_type.strip().upper()
    if ctype == "ECS":
        return bool(ECS_CLUSTER_ARN_RE.match(arn))
    if ctype == "EKS":
        return bool(EKS_CLUSTER_ARN_RE.match(arn))
    return False


def arn_region(arn):
    """Extract the Region segment from an ARN, or None.

    ARNs are of the form arn:partition:service:region:account:resource.
    Returns the region field (index 3) when present and non-empty, else None.
    Used for the same-Region warning on manually entered cluster ARNs (R7a.3).

    Args:
        arn: The ARN string (may be None or non-string).

    Returns:
        The Region string, or None if not extractable.
    """
    if not isinstance(arn, str):
        return None
    parts = arn.strip().split(':')
    if len(parts) >= 4 and parts[0] == 'arn' and parts[3]:
        return parts[3]
    return None


def arn_account(arn):
    """Extract the account-id segment from an ARN, or None.

    Returns the account field (index 4) when present and non-empty, else None.
    Used for the same-account warning on manually entered cluster ARNs (R7a.3)
    and for ownership detection of listed associations.

    Args:
        arn: The ARN string (may be None or non-string).

    Returns:
        The account-id string, or None if not extractable.
    """
    if not isinstance(arn, str):
        return None
    parts = arn.strip().split(':')
    if len(parts) >= 5 and parts[0] == 'arn' and parts[4]:
        return parts[4]
    return None
